# Generated by Django 5.1.3 on 2025-05-09 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_rename_products_cars_alter_cars_options'),
        ('deals', '0002_alter_order_options_alter_orderitem_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='cars.cars', verbose_name='Автомобиль'),
        ),
        migrations.AlterModelTable(
            name='order',
            table='deal',
        ),
    ]
