# Generated by Django 5.1.3 on 2025-05-10 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0003_alter_orderitem_product_alter_order_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='order',
            table='order',
        ),
    ]
