# Generated by Django 5.1.3 on 2025-05-09 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_products_options'),
        ('carts', '0001_initial'),
        ('deals', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Cars',
        ),
        migrations.AlterModelOptions(
            name='cars',
            options={'ordering': ('id',), 'verbose_name': 'Автомобиль', 'verbose_name_plural': 'Автомобили'},
        ),
    ]
