# Generated by Django 5.1.3 on 2025-05-17 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_alter_cars_price'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cars',
            table='vehicle',
        ),
    ]
