# Generated by Django 5.1.3 on 2025-05-17 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_alter_cars_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cars',
            table='product',
        ),
    ]
